### PR TITLE
Documentation: cheat-sheet examples from Gif written out

### PR DESCRIPTION
**Pull request by sdenham**
- Copied out cheat-sheet commands from main README gif into examples/README.md

As [requested here](https://github.com/birdayz/kaf/issues/143)

This is my first open-source PR so apologies in advance for the inevitable rookie mistakes. Eager learn the community norms

### CODE REVIEW

**Comment by birdayz** [comment]
thanks so much! what do you think about moving these to the top-level README?

**Comment by sdenham** [comment]
I'd be all for that! Was thinking you mightn't want to clutter it with content which is already there in an appealing format. Wherever you're more comfortable. Lmk and I can make the change

**Comment by birdayz** [comment]
yeah, please add it to the main README, it's more visible that way. thank you!

**Comment by birdayz** [comment]
thanks!

**Pull request merged**
