### PR TITLE
fix: --config is ignored

### PR DESCRIPTION
**Pull request by robsonpeixoto**

### CODE REVIEW

**Comment by birdayz** [comment]
please remove the changes to go.mod / go.sum, i suppose these are unintentional

**Comment by robsonpeixoto** [comment]
I updated because of that: `This release also fixes the repo's go.mod file to be compatible with Go 1.13.`

But I can downgrade if you wish

**Comment by robsonpeixoto** [comment]
@birdayz done

**Comment by birdayz** [comment]
Thanks!

**Pull request merged**
