### PR TITLE
Add integration tests for some of the commands

### PR DESCRIPTION
**Pull request by orlangure**
This commit adds integration tests for a part of available commands.
This is achieved by using [Gnomock](https://github.com/orlangure/gnomock) [Kafka](https://github.com/orlangure/gnomock/tree/master/preset/kafka) preset which spins up a
temporary Kafka container, and executing CLI commands against it.

To support integration tests, I had to make a couple of changes to
non-test code:

1. I added context to a couple of places to support cobra's
   `ExecuteContext` function. The reason behind it was that `consume`
   command does not exit automatically, and there needed to be a way to
   cancel it after some time. For that I used `context.WithTimeout`, and
   pushed this context into consumer code. Now consumer code either
   passes context forward, or listens to cancellation event itself.
2. I changed all of the commands to use configurable stdin, stdout and
   stderr streams. Cobra supports using custom input/output objects, but
   all the actual commands used `os.Stdout` directly. I implemented a
   `PersistentPreRun` function on `rootCmd` that decides which
   reader/writer to use: by default we always use os descriptors.

### CODE REVIEW

**Comment by birdayz** [comment]
this is really cool. thanks for your work, will hopefully look at it this evening!

**Comment by birdayz** [comment]
thank you!

**Comment by orlangure** [comment]
Thank you!
Would you like to try and add these tests to your CI pipeline?
I only tried running these tests in github actions, but I hope circleci is similar.

**Comment by birdayz** [comment]
it did not work. probably a problem with docker access..do you have a recommended setup for circleci?

**Comment by orlangure** [comment]
Gnomock requires a running docker daemon, and from the [circleci docs](https://circleci.com/docs/2.0/building-docker-images/) I see that they support it:

```
jobs:
  build:
    steps:
      # ... steps for building/testing app ...

      - setup_remote_docker:
        version: 19.03.13
```

Can you try this configuration?

**Comment by birdayz** [comment]
tbh circleci is a bit of a PITA here, i'll probably switch CI to github actions anyway. will add the integrationtests then

**Comment by birdayz** [comment]
switched to actions, it works like a charm. thanks !

**Pull request merged**
